### ISSUE TITLE
Russian localization update (`ru_ru.json`)

### ISSUE THREAD

**Issue by mpustovoi** [muon-rw/Charm#20]
Due to the limitations of the GitHub, I can't make a fork for the fork of the original mod repository, where I have already created a pull request, that's not merged yet.

However, due to the inactivity of the original mod, I believe my PR will be hanging there for a long time.

Therefore, here is the same update of `assets/charm/ru_ru.json` that I sent there: [`ru_ru.json`](https://github.com/user-attachments/files/17922698/ru_ru.json).
You can also find it [here](https://github.com/svenhjol/Charm/blob/024e927fdfc1d70bc756f493eb56d1a9ad20f75a/src/main/resources/assets/charm/lang/en_us.json) in my fork.

I also noticed that the original mod lacks a translation key for the `echolocation` effect description (used for mods like **JEED** or **EMIffect**):
```json
  "effect.charm.echolocation.description": "Causes all living entities around the player to glow. Can be obtained by using Bat in a Bucket."
```
I took it from the original mod's wiki.

If you find this kind of contribution to the mod too clumsy, I'll understand.

**Comment by muon-rw** [comment]
I don't mind this format, I appreciate the update!
